config/routes.rb
Rails.application.routes.draw do
  root to: 'journey#geoloc_start'
  get "agence/:lname", to: "journey#geoloc_start", as: "agency_start_page"
  get "scroll", to: "pages#scroll"

  namespace :api do
    get "agency/details", to: "agencies#show", as: "agency"
  end

  namespace :dashboard do
    get "start", to: "agencies#start", as: "agency"
    get "surveys", to: "agencies#surveys", as: "surveys"
    get "agent_creation", to: "agencies#create_agent", as: "create_agent"
    get "agency_agents", to: "agencies#agents", as: "agency_agents"
    get "survey/:id", to: "agencies#survey", as: "survey"
    resources :agents
  end

  devise_for :customers, controllers: { sessions: 'customers/sessions', registrations: 'customers/registrations' }, path_names: { sign_in: 'connexion', sign_up: "inscription" }
  devise_for :agencies, controllers: { sessions: 'agencies/sessions', registrations: 'agencies/registrations' }, path_names: {sign_in: 'connexion', sign_up: "inscription" }
  devise_for :agents, controllers: { sessions: 'agents/sessions', registrations: 'agents/registrations' }, path_names: {sign_in: 'connexion', sign_up: "inscription" }

  resources :questions
  resources :answers
  resources :conditions
  resources :sentences
  resources :front_conditions

  post "questions/test", to: "questions#test", as: "test"

  get "journey/geoloc_start", to: "journey#geoloc_start", as: "geoloc_start_journey"
  post "questionnaire(/:lname)", to: "journey#start", as: "start_journey"
  post "next_question", to: "journey#next_question", as: "next_question"
  post "next_question_skip", to: "journey#next_question_skip", as: "next_question_skip"
  get "journey/resume/:id", to: "journey#resume", as: "resume"
  post "change_answer_order", to: "answers#change_order", as: "change_answer_order"

  get "export_select_values", to: "conditions#export_select_values", as: "export_select_values"

  get "/404", to: "errors#not_found", as: "not_found"
  get "/500", to: "errors#internal_error", as: "internal_error"

  get '*unmatched_route', to: 'application#not_found_redirect'

end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Orderable
  include GlobalID::Identification
  orderable
  has_many :answers, dependent: :destroy
  has_many :conditions, dependent: :destroy
  has_one :sentence, dependent: :destroy
  has_one :front_condition, dependent: :destroy

  field :position, type: Integer
  field :type, type: String
  field :required, type: Boolean
  field :field_name, type: String
  field :label, type: String
  field :theme, type: String
  field :hint, type: String, default: nil
  field :js_validation, type: Boolean, default: false
  field :js_validation_min_value, type: Integer, default: nil
  field :exit_step, type: Boolean
  field :exit_index, type: Integer
  field :radio_by_pair, type: Boolean
  field :field_in_label_to_display, type: String
  field :text_to_display_after_variable, type: String, default: nil
  field :specific_display, type: Boolean, default: nil

  def answers_words_size
    self.answers.map{|answer| answer.text}.compact.map{|text| text.chars.size}.compact.sum
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :find_question, only: [:show, :update, :destroy, :edit]

  def show
  end

  def index
    # handle_totals
    puts Survey.fields.except("_id","created_at","updated_at", "position").keys
    @questions = Question.all
  end

  def handle_totals
    points = []
    [:personality, :temperament_features, :house_works, :couple_choice].each do |field|
      points << Question.find_by(field_name: "#{field.to_s}").answers.map{|answer| answer.scoring_points}
    end
    start_hash = {rational: 0, affective: 0, undecided: 0, bold: 0}
    points.flatten.each do |points_hash|
      start_hash[:rational] += points_hash["rational"].to_i
      start_hash[:affective] += points_hash["affective"].to_i
      start_hash[:undecided] += points_hash["undecided"].to_i
      start_hash[:bold] += points_hash["bold"].to_i
    end
    puts "---- Handle Totals ----"
    puts start_hash.inspect
    puts "-----------------------"
  end

  def create
    @question = Question.new(safe_params)
    if @question.save
      redirect_to questions_path, notice: "Bravo, question créee"
    else
      render :new
    end
  end

  def new
    @last_question_position = Question.all.map{|question| question.position}.sort.last.to_i + 1
    puts "Last question position"
    puts @last_question_position
    @question = Question.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def test
    puts ajax_safe_params.inspect
    render json: {test: "success"}.as_json, status: :ok
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def safe_params
    params.require(:question).permit(:position, :type, :required, :field_name, :label, :theme)
  end

  def ajax_safe_params
    params.except(:controller,:action).permit(:question, :type)
  end

end

app/views/questions/index.html.haml
.container
  .d-flex.justify-content-center.align-items-center.my-5
    = remote_link_to("Ajax trigger test", test_path, class: "ajax-trigger btn btn-dark", params: {question: 1, type: "text"})

  .d-flex.justify-content-center.align-items-center.my-5
    = link_to "Créer une question", new_question_path, class: "btn btn-dark"

  .table-responsive
    %table.table
      %thead
        %tr
          %th{scope: "col"} Position
          %th{scope: "col"} Label
          %th{scope: "col"} Type
          %th{scope: "col"} Field name
          %th{scope: "col"} Theme
          %th{scope: "col"} Required
          %th{scope: "col"} Réponses
          %th{scope: "col"} Conditions
          %th{scope: "col"} Actions
      %tbody
      - @questions.sort_by{|question| question.position}.each_with_index do |question,index|
        %tr
          %th.d-flex.justify-content-start.align-items-center{scope: "row"}
            = question.position
          %td
            = "#{question.label}"
          %td
            = "#{question.type.capitalize}"
          %td
            = "#{question.field_name}"
          %td
            = "#{question.theme.capitalize}"
          %td
            - if question.required
              = "Obligatoire"
            - else
              = "Facultatif"
          %td
            = question.answers.size
          %td
            = question.conditions.size
          %td
            = link_to "Show", question_path(question)

app/views/questions/new.html.haml
.container
  = simple_form_for @question do |f|
    = f.input :position, input_html: {class: "form-control", value: "#{@last_question_position}"}
    = f.input :field_name, collection: Survey.sanitize_fields, input_html: {class: "form-control"}
    = f.input :label, input_html: {class: "form-control"}


    .d-flex.justify-content-between.align-items-center.mt-5.mb-3
      .custom-label Le type de champ
    .d-flex.justify-content-start.align-items-center.mb-4.custom-radio-container
      - InputType.list_with_datas.each do |type|
        .custom-radio-input
          %input{type: "radio", name: "question[type]", id: "#{type[:name]}", value: "#{type[:name]}"}
          %label{for: "#{type[:name]}"}
            = type[:name].to_s.capitalize

    .line-separator

    .d-flex.justify-content-between.align-items-center.mt-5.mb-3
      .custom-label Le thème de la question
    .d-flex.justify-content-between.align-items-center.mb-4.custom-radio-container
      .d-flex.justify-content-start.align-items-center
        - SurveyTheme.list_with_datas.each_with_index do |theme,index|
          .custom-radio-input
            %input{type: "radio", name: "question[theme]", id: "#{theme[:name]}", value: "#{theme[:name]}", "data-index": "#{index + 1}"}
            %label{for: "#{theme[:name]}"}
              = theme[:name].to_s.capitalize
      .d-flex.justify-content-end.align-items-center.d-none
        - SurveyTheme.list_with_datas.each_with_index do |theme,index|
          %aside.d-none{"data-index": "#{index + 1}"}
            = "#{theme[:details]}"

    .line-separator

    .custom-boolean-input.mb-5
      %input{type: "hidden", value: "false", name: "question[required]"}
      %input{type: "checkbox", value: "true", name: "question[required]", id: "question_required"}
      %label{for: "question_required"} Question obligatoire
      .hint En cochant cette option, cette question sera obligatoire

    .d-flex.justify-content-center.align-items-center
      = f.submit "Valider", class: "btn btn-dark btn-sm"

app/views/questions/show.html.haml
%section.questions
  .big-title La question
  .question-container
    .question-item
      .question-item-title Position
      .question-item-value
        = @question.position

    .question-item
      .question-item-title Label
      .question-item-value
        = @question.label

    .question-item
      .question-item-title Field name
      .question-item-value
        = @question.field_name

    .question-item
      .question-item-title Theme
      .question-item-value
        = @question.theme

    .question-item
      .question-item-title Type
      .question-item-value
        = @question.type

    .question-item
      .question-item-title Statut
      .question-item-value
        - if @question.required
          = "Obligatoire"
        - else
          = "Facultative"

  .d-flex.justify-content-between.align-items-center
    .big-title Validation front
    = link_to "Nouvelle", new_front_condition_path(question: @question), class: "btn btn-dark btn-sm"

  .d-flex.justify-content-between.align-items-center
    .big-title Les réponses
    = link_to "Nouvelle", new_answer_path(question: @question), class: "btn btn-dark btn-sm"

  .d-flex.justify-content-between.align-items-center
    .big-title Les conditions
    = link_to "Nouvelle", new_condition_path(question: @question), class: "btn btn-dark btn-sm"

  - if !@question.sentence?
    .d-flex.justify-content-between.align-items-center
      .big-title La phrase
      = link_to "Nouvelle", new_sentence_path(question: @question), class: "btn btn-dark btn-sm"


  .answers-container
    - @question.answers.sort_by{|answer| answer.order}.each do |answer|
      = render "questions/partials/answer_#{@question.type}", answer: answer



  .conditions-container
    = "Cette question s'affiche si le champ "
    - @question.conditions.each do |condition|
      = condition.field_name
      = " est "
      = condition.operator
      = " à "
      = condition.value
  .sentences-container
    - if @question.sentence?
      = @question.sentence.text