config/routes.rb
Rails.application.routes.draw do
  root to: 'journey#geoloc_start'
  get "agence/:lname", to: "journey#geoloc_start", as: "agency_start_page"
  get "scroll", to: "pages#scroll"

  namespace :api do
    get "agency/details", to: "agencies#show", as: "agency"
  end

  namespace :dashboard do
    get "start", to: "agencies#start", as: "agency"
    get "surveys", to: "agencies#surveys", as: "surveys"
    get "agent_creation", to: "agencies#create_agent", as: "create_agent"
    get "agency_agents", to: "agencies#agents", as: "agency_agents"
    get "survey/:id", to: "agencies#survey", as: "survey"
    resources :agents
  end

  devise_for :customers, controllers: { sessions: 'customers/sessions', registrations: 'customers/registrations' }, path_names: { sign_in: 'connexion', sign_up: "inscription" }
  devise_for :agencies, controllers: { sessions: 'agencies/sessions', registrations: 'agencies/registrations' }, path_names: {sign_in: 'connexion', sign_up: "inscription" }
  devise_for :agents, controllers: { sessions: 'agents/sessions', registrations: 'agents/registrations' }, path_names: {sign_in: 'connexion', sign_up: "inscription" }

  resources :questions
  resources :answers
  resources :conditions
  resources :sentences
  resources :front_conditions

  post "questions/test", to: "questions#test", as: "test"

  get "journey/geoloc_start", to: "journey#geoloc_start", as: "geoloc_start_journey"
  post "questionnaire(/:lname)", to: "journey#start", as: "start_journey"
  post "next_question", to: "journey#next_question", as: "next_question"
  post "next_question_skip", to: "journey#next_question_skip", as: "next_question_skip"
  get "journey/resume/:id", to: "journey#resume", as: "resume"
  post "change_answer_order", to: "answers#change_order", as: "change_answer_order"

  get "export_select_values", to: "conditions#export_select_values", as: "export_select_values"

  get "/404", to: "errors#not_found", as: "not_found"
  get "/500", to: "errors#internal_error", as: "internal_error"

  get '*unmatched_route', to: 'application#not_found_redirect'

end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Orderable
  include GlobalID::Identification
  orderable
  has_many :answers, dependent: :destroy
  has_many :conditions, dependent: :destroy
  has_one :sentence, dependent: :destroy
  has_one :front_condition, dependent: :destroy

  field :position, type: Integer
  field :type, type: String
  field :required, type: Boolean
  field :field_name, type: String
  field :label, type: String
  field :theme, type: String
  field :hint, type: String, default: nil
  field :js_validation, type: Boolean, default: false
  field :js_validation_min_value, type: Integer, default: nil
  field :exit_step, type: Boolean
  field :exit_index, type: Integer
  field :radio_by_pair, type: Boolean
  field :field_in_label_to_display, type: String
  field :text_to_display_after_variable, type: String, default: nil
  field :specific_display, type: Boolean, default: nil

  def answers_words_size
    self.answers.map{|answer| answer.text}.compact.map{|text| text.chars.size}.compact.sum
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :find_question, only: [:show, :update, :destroy, :edit]

  def show
  end

  def index
    # handle_totals
    puts Survey.fields.except("_id","created_at","updated_at", "position").keys
    @questions = Question.all
  end

  def handle_totals
    points = []
    [:personality, :temperament_features, :house_works, :couple_choice].each do |field|
      points << Question.find_by(field_name: "#{field.to_s}").answers.map{|answer| answer.scoring_points}
    end
    start_hash = {rational: 0, affective: 0, undecided: 0, bold: 0}
    points.flatten.each do |points_hash|
      start_hash[:rational] += points_hash["rational"].to_i
      start_hash[:affective] += points_hash["affective"].to_i
      start_hash[:undecided] += points_hash["undecided"].to_i
      start_hash[:bold] += points_hash["bold"].to_i
    end
    puts "---- Handle Totals ----"
    puts start_hash.inspect
    puts "-----------------------"
  end

  def create
    @question = Question.new(safe_params)
    if @question.save
      redirect_to questions_path, notice: "Bravo, question créee"
    else
      render :new
    end
  end

  def new
    @last_question_position = Question.all.map{|question| question.position}.sort.last.to_i + 1
    puts "Last question position"
    puts @last_question_position
    @question = Question.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def test
    puts ajax_safe_params.inspect
    render json: {test: "success"}.as_json, status: :ok
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def safe_params
    params.require(:question).permit(:position, :type, :required, :field_name, :label, :theme)
  end

  def ajax_safe_params
    params.except(:controller,:action).permit(:question, :type)
  end

end

app/views/questions/partials/_answer_checkbox.html.haml
.answer-item
  .answer-item-block
    .answer-item-block-title Order
    .answer-item-block-value
      = answer.order
  .answer-item-block.f-grow
    .answer-item-block-title Text
    .answer-item-block-value
      = answer.text
  .answer-item-block
    .answer-item-block-title Increment id
    .answer-item-block-value
      = answer.increment_id
  .answer-item-block
    .answer-item-block-title Actions
    .answer-item-block-value
      = link_to "Edit", edit_answer_path(answer, question: @question.id)
      = link_to "Delete", answer_path(answer), method: :delete, alert: "Etes-vous sûr ?"
  = simple_form_for :answer, url: change_answer_order_path, method: :post do |f|
    = f.input :id, as: :hidden, input_html: {value: answer.id.to_s}
    = f.submit "Changer l'ordre", class: "btn btn-dark"
    - @question.answers.sort_by{|answ| answ.order}.each_with_index do |answ,index|
      - if answ.order == answer.order
        = tag.input type: :radio, name: "answer[new_order]", value: answ.order, disabled: true, id: "#{answer.order}-#{answ.order}-#{index+1}"
        = label_tag "#{answer.order}-#{answ.order}-#{index+1}", answ.order
      - else
        = tag.input type: :radio, name: "answer[new_order]", value: answ.order, id: "#{answer.order}-#{answ.order}-#{index+1}"
        = label_tag "#{answer.order}-#{answ.order}-#{index+1}", answ.order

app/views/questions/partials/_answer_geocode.html.haml
.answer-item
  .answer-item-block
    .answer-item-block-title Order
    .answer-item-block-value
      = answer.order
  .answer-item-block.f-grow
    .answer-item-block-title Text
    .answer-item-block-value
      = answer.text
  .answer-item-block
    .answer-item-block-title Increment id
    .answer-item-block-value
      = answer.increment_id
  .answer-item-block
    .answer-item-block-title Actions
    .answer-item-block-value
      = link_to "Edit", edit_answer_path(answer, question: @question.id)

app/views/questions/partials/_answer_number.html.haml
.answer-item
  .answer-item-block
    .answer-item-block-title Order
    .answer-item-block-value
      = answer.order
  .answer-item-block.f-grow
    .answer-item-block-title Text
    .answer-item-block-value
      = answer.text
  .answer-item-block
    .answer-item-block-title Increment id
    .answer-item-block-value
      = answer.increment_id
  .answer-item-block
    .answer-item-block-title Actions
    .answer-item-block-value
      = link_to "Edit", edit_answer_path(answer, question: @question.id)

app/views/questions/partials/_answer_radio.html.haml
.answer-item
  .answer-item-block
    .answer-item-block-title Order
    .answer-item-block-value
      = answer.order
  .answer-item-block.f-grow
    .answer-item-block-title Text
    .answer-item-block-value
      = answer.text
  .answer-item-block
    .answer-item-block-title Increment id
    .answer-item-block-value
      = answer.increment_id
  .answer-item-block
    .answer-item-block-title Actions
    .answer-item-block-value
      = link_to "Edit", edit_answer_path(answer, question: @question.id)
  = simple_form_for :answer, url: change_answer_order_path, method: :post do |f|
    = f.input :id, as: :hidden, input_html: {value: answer.id.to_s}
    = f.submit "Changer l'ordre", class: "btn btn-dark"
    - @question.answers.sort_by{|answ| answ.order}.each_with_index do |answ,index|
      - if answ.order == answer.order
        = tag.input type: :radio, name: "answer[new_order]", value: answ.order, disabled: true, id: "#{answer.order}-#{answ.order}-#{index+1}"
        = label_tag "#{answer.order}-#{answ.order}-#{index+1}", answ.order
      - else
        = tag.input type: :radio, name: "answer[new_order]", value: answ.order, id: "#{answer.order}-#{answ.order}-#{index+1}"
        = label_tag "#{answer.order}-#{answ.order}-#{index+1}", answ.order

app/views/questions/partials/_answer_text.html.haml
.answer-item
  .answer-item-block
    .answer-item-block-title Order
    .answer-item-block-value
      = answer.order
  .answer-item-block.f-grow
    .answer-item-block-title Placeholder
    .answer-item-block-value
      = answer.placeholder
  .answer-item-block
    .answer-item-block-title Increment id
    .answer-item-block-value
      = answer.increment_id
  .answer-item-block
    .answer-item-block-title Actions
    .answer-item-block-value
      = link_to "Edit", edit_answer_path(answer, question: @question.id)

app/views/questions/partials/_answer_textarea.html.haml
.answer-item
  .answer-item-block
    .answer-item-block-title Order
    .answer-item-block-value
      = answer.order
  .answer-item-block.f-grow
    .answer-item-block-title Text
    .answer-item-block-value
      = answer.text
  .answer-item-block
    .answer-item-block-title Increment id
    .answer-item-block-value
      = answer.increment_id
  .answer-item-block
    .answer-item-block-title Actions
    .answer-item-block-value
      = link_to "Edit", edit_answer_path(answer, question: @question.id)