config/routes.rb
Rails.application.routes.draw do
  root to: 'journey#geoloc_start'
  get "agence/:lname", to: "journey#geoloc_start", as: "agency_start_page"
  get "scroll", to: "pages#scroll"

  namespace :api do
    get "agency/details", to: "agencies#show", as: "agency"
  end

  namespace :dashboard do
    get "start", to: "agencies#start", as: "agency"
    get "surveys", to: "agencies#surveys", as: "surveys"
    get "agent_creation", to: "agencies#create_agent", as: "create_agent"
    get "agency_agents", to: "agencies#agents", as: "agency_agents"
    get "survey/:id", to: "agencies#survey", as: "survey"
    resources :agents
  end

  devise_for :customers, controllers: { sessions: 'customers/sessions', registrations: 'customers/registrations' }, path_names: { sign_in: 'connexion', sign_up: "inscription" }
  devise_for :agencies, controllers: { sessions: 'agencies/sessions', registrations: 'agencies/registrations' }, path_names: {sign_in: 'connexion', sign_up: "inscription" }
  devise_for :agents, controllers: { sessions: 'agents/sessions', registrations: 'agents/registrations' }, path_names: {sign_in: 'connexion', sign_up: "inscription" }

  resources :questions
  resources :answers
  resources :conditions
  resources :sentences
  resources :front_conditions

  post "questions/test", to: "questions#test", as: "test"

  get "journey/geoloc_start", to: "journey#geoloc_start", as: "geoloc_start_journey"
  post "questionnaire(/:lname)", to: "journey#start", as: "start_journey"
  post "next_question", to: "journey#next_question", as: "next_question"
  post "next_question_skip", to: "journey#next_question_skip", as: "next_question_skip"
  get "journey/resume/:id", to: "journey#resume", as: "resume"
  post "change_answer_order", to: "answers#change_order", as: "change_answer_order"

  get "export_select_values", to: "conditions#export_select_values", as: "export_select_values"

  get "/404", to: "errors#not_found", as: "not_found"
  get "/500", to: "errors#internal_error", as: "internal_error"

  get '*unmatched_route', to: 'application#not_found_redirect'

end

app/models/agency.rb
class Agency
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Phony

  has_one :custom_style
  has_many :surveys
  has_many :agents

  field :name, type: String
  field :photo_url, type: String
  field :website_url, type: String
  field :phone, type: String
  field :facebook_url, type: String
  field :email, type: String
  field :contact_email, type: String
  field :aristid_email, type: String
  field :aristid_url, type: String

end

app/controllers/agencies/registrations_controller.rb
class Agencies::RegistrationsController < Devise::RegistrationsController

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :lastname, :firstname, :city, :country, :phone_number, :cgu, :promo_code])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :lastname, :firstname, :city, :country, :phone_number, :cgu, :promo_code])
  end

  def after_sign_up_path_for(resource)
    resume_path(resource)
  end

  def after_update_path_for(resource)
    root_path
  end

end

app/controllers/agencies/sessions_controller.rb
class Agencies::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  after_action :after_login, only: [:create]

  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end

  protected

  def after_login
  end

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute, :cgu])
  end

  def after_sign_in_path_for(resource)
    dashboard_agency_path
  end

end

app/controllers/api/agencies_controller.rb
class Api::AgenciesController < ApplicationController

  def show
    if params[:email]
      email = params[:email].remove("<",">").strip
      puts "---- Email Inspector ----"
      puts email.inspect
      puts "-------------------------"
      @agency = Agency.find_by(aristid_email: email)
      if @agency
        puts "---- Inside aristid API Agency infos ----"
        puts @agency.inspect
        puts "-----------------------------------------"
        render json: {agency: @agency}, status: :ok
      else
        puts "Agency with email: #{email} does not exsist !!"
        render json: {error: "Agency with email: #{email}  does not exsist"}, status: 400
      end
    else
      render json: {error: "Email param must be inside your request"}, statut: 400
    end
  end

end

app/controllers/dashboard/agencies_controller.rb
class Dashboard::AgenciesController < ApplicationController
  before_action :authenticate_agent!

  def start
    @agent = current_agent
    @agency = @agent.agency
  end

  def create_agent
    @agent = current_agent
    @agency = @agent.agency
  end

  def agents
    @agent = current_agent
    @agency = @agent.agency
    @agents = @agency.agents
  end

  def surveys
    @agent = current_agent
    @agency = @agent.agency
    @surveys = @agency.surveys
  end

  def survey
    @agent = current_agent
    @agency = @agent.agency
    @survey = Survey.find(params[:id])
    if @survey.survey_scoring
      @scoring = @survey.survey_scoring.personality
      values = {datas: [@scoring["undecided"], @scoring["bold"], @scoring["affective"], @scoring["rational"]]}
      generate_gon_variables(values)
    end
  end

  private

  def generate_gon_variables(hashed_values)
    gon.push(hashed_values)
  end

end

app/controllers/dashboard/agents_controller.rb
class Dashboard::AgentsController < ApplicationController
  respond_to :html

  def new
    @agent = current_agent
    @new_agent = Agent.new
    @agency = @agent.agency
  end

  def create
    puts params[:agent][:agent_role].inspect
    puts params[:agent][:agent_role].class
    @agency = current_agent.agency
    @agent = Agent.new(safe_params)
    if @agent.save
      puts "Success agent creation"
      redirect_to dashboard_agency_path
    else
      puts @agent.errors.full_messages
      @new_agent = @agent
      # render json: {errors: @agent.errors.full_messages}, status: :ok
      respond_with(@agent, location: "/dashboard/agents/new")
    end
  end

  private

  def safe_params
    params.require(:agent).permit(:email, :firstname, :lastname, :agent_role, :password, :password_confirmation, :agency_id)
  end

end

app/views/dashboard/agencies/agents.html.haml
.container
  %h4
    = "Les agents de l'agence #{@agency.name}"
  - @agents.each_with_index do |agent,index|
    .d-flex.align-items-start.justify-content-start
      %b
        = index+1
      = agent_fullname(agent.firstname,agent.lastname)
      = agent.email
      = agent.phone
      = agent.agent_role.name
      = agent.active

app/views/dashboard/agencies/create_agent.html.haml
= "Créer un agent"

app/views/dashboard/agencies/start.html.haml
%section.aristid-dashboard
  %section.menu
    = render "dashboard/agencies/partials/fixed_menu"
  %section.content
    = render "dashboard/agencies/partials/account_menu"
    .fullheight-content
      .square-navigation-wrapper
        .circle-overlay
          .circle-item
            = svg("logo-aristid-visage")
            %p
              = "Bienvenue !"
            %p
              = "Moi c'est Aristid ,"
            %p
              = "à votre service."
        .navigation-top-line
          = link_to dashboard_agency_path do
            .navigation-item.red
              .fixed-size-svg-wrapper
                = feather_svg("user-plus")
              = "Ajouter un contact"
              .beta-feature.top-position
                = feather_svg("unicon-beta")
                .strong Bientôt disponible
          = link_to dashboard_surveys_path do
            .navigation-item.light-red
              .fixed-size-svg-wrapper
                = feather_svg("users")
              = "Mes contacts"
        .navigation-bottom-line
          = link_to dashboard_agency_path do
            .navigation-item.light-blue
              .fixed-size-svg-wrapper
                = feather_svg("bar-chart")
              = "Mon tableau de bord"
              .beta-feature.bottom-position
                = feather_svg("unicon-beta")
                .strong Bientôt disponible
          = link_to dashboard_agency_path do
            .navigation-item.blue
              .fixed-size-svg-wrapper
                = feather_svg("unicon-store")
              = "Mes biens"
              .beta-feature.bottom-position
                = feather_svg("unicon-beta")
                .strong Bientôt disponible

%section.agency-resume-block.d-none
  .agency-block.mb-4
    %h4 Agence
    = @agency.inspect
    .agency-svg-logo
      = svg("#{@agency.custom_style.logo}-logo")
    %p
      = "Site web de l'agence"
    - if @agency.website_url
      = link_to @agency.website_url, @agency.website_url, class: "btn btn-primary"
    = @agency.website_url
  .agent-block.mb-4
    %h4 Les agents
    - @agency.agents.each_with_index do |agent,index|
      .agent-item
        %b
          = index+1
        .agent-email
          = agent.email
        = agent.firstname
        = agent.lastname
        = agent.agent_role.name
        = agent.phone
  .surveys-block.mb-4
  .actions-block
    = link_to "Déconnexion", destroy_agent_session_path, method: :delete, class: "btn btn-primary", data: {confirm: "Attention !!"}
    = render "dashboard/agencies/partials/actions"

app/views/dashboard/agencies/survey.html.haml
%section.aristid-dashboard
  %section.menu
    = render "dashboard/agencies/partials/fixed_menu"
  %section.content.start-aligned
    = render "dashboard/agencies/partials/account_menu"
    .fullpage-content
      .page-title-column
        .title Fiche client
        - if request.referer.present?
          = link_to request.referer do
            .feather-svg-fadegreen
              = feather_svg("arrow-left")
            .backlink Retour aux contacts
        - else
          = link_to default_path do
            = feather_svg("arrow-left")
            .backlink Retour aux contacts
      %section.survey-wrapper
        %section.survey-menu
          - if @survey.customer
            = render "dashboard/agencies/partials/customer"
        %section.survey-content
          %ul.nav{:role => "tablist"}
            %li.nav-item
              %a.nav-link.active{"aria-controls" => "pills-home", "aria-selected" => "true", "data-toggle" => "tab", :href => "#pills-project", :role => "tab"} Projet
            %li.nav-item
              %a.nav-link{"aria-controls" => "pills-profile", "aria-selected" => "false", "data-toggle" => "tab", :href => "#pills-context", :role => "tab"} Contexte
            %li.nav-item
              %a.nav-link{"aria-controls" => "pills-contact", "aria-selected" => "false", "data-toggle" => "tab", :href => "#pills-profil", :role => "tab"} Profil
            %li.nav-item
              %a.nav-link{"aria-controls" => "pills-contact", "aria-selected" => "false", "data-toggle" => "tab", :href => "#pills-actions", :role => "tab"} Actions

          .tab-content
            #pills-project.tab-pane.fade.show.active{"aria-labelledby" => "pills-home-tab", :role => "tabpanel"}
              = render "dashboard/agencies/partials/project"
            #pills-context.tab-pane.fade{"aria-labelledby" => "pills-profile-tab", :role => "tabpanel"}
              = render "dashboard/agencies/partials/context"
            #pills-profil.tab-pane.fade{"aria-labelledby" => "pills-contact-tab", :role => "tabpanel"}
              - if @survey.survey_scoring
                = render "dashboard/agencies/partials/profile"
            #pills-actions.tab-pane.fade{"aria-labelledby" => "pills-contact-tab", :role => "tabpanel"}
              = "Les actions"

app/views/dashboard/agencies/surveys.html.haml
%section.aristid-dashboard
  %section.menu
    = render "dashboard/agencies/partials/fixed_menu"
  %section.content.start-aligned
    = render "dashboard/agencies/partials/account_menu"
    .fullpage-content
      .page-title Tous les contacts
      #aristid-agency-table
        %table.table.agency-dashboard-table
          %thead
            %tr
              %th.sort{"data-sort": "date"}
                Crée le
                = feather_svg("code")
              %th.sort{"data-sort": "name"}
                Prénom Nom
                = feather_svg("code")
              %th.sort{"data-sort": "type"}
                Logement
                = feather_svg("code")
              %th.sort{"data-sort": "surface"}
                Surface
                = feather_svg("code")
              %th.sort{"data-sort": "budget"}
                Budget
                = feather_svg("code")
              %th{scope: "col"} Localisation
          %tbody.list
            - @surveys.each_with_index do |survey,index|
              %tr
                %th{:scope => "row"}
                  .date
                    = l(survey.created_at, format: :medium)
                %td
                  .name
                    - if survey.customer
                      = "#{survey.customer.firstname} #{survey.customer.lastname}"
                %td
                  = survey.property_type
                %td
                  .surface
                    = "#{survey.surface} m²"
                %td
                  .budget
                    - if survey.budget
                      = "#{number_with_delimiter(survey.budget.reject(&:empty?).first.to_i, delimiter: " ")} €"
                %td
                  - if survey.cities
                    = survey.cities.join("-")
                  = link_to dashboard_survey_path(survey) do
                    .table-action
                      .feather-svg-lightred
                        = feather_svg("chevron-right")
        .fixed-pagination
          %ul.pagination

%script{src: "//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"}